# This workflow will perform a build of the project and run tests

name: Build and check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows to run from the Actions tab
  workflow_dispatch:

# Disabled as it requires a local build of Apache POI
#jobs:
#  build-and-test:
#    uses: centic9/actions/.github/workflows/gradle-build.yml@4

# Use an empty job for now
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Just provide information that this build does not do anything currently
        run: echo Cannot run CI for now as building requires a local checkout and build of Apache POI
